# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuna@0.36.1" do
  version "0.36.1"

  on_macos do
    on_arm do
      sha256 "8837d90afc4b7d72aed6e955e8fafa87267bdff29cbc103538adfaede80efdae"
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f6d7b2a946ccf5a0d70717ccd9e692de8e844dd3b6ddc6651766a47edebe896a"
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4d1b69545e5a51fbfd4c563476786b027ecc9564e0174ee36f6af10896d0ab84"
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b7025ab9ec9827181d2c01338710609c5126e28361897540eb8b63cf0ed224e"
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tuna@0.36.1"
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuna"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuna"]
    end
  end

  # No zap stanza required
end
