# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuna" do
  version "0.35.1"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_darwin_amd64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "fc2c115bc7b7a42d1dee1e77ca266944f06422368a4fefafcb0c69e3b7507259"
    end
    on_arm do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_darwin_arm64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "b50acea0f0ea6292a302c69c378b86d9f8d7c7bf39e46525d593ac83f9da004b"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_linux_amd64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "1f04bf4d7def55c3b5b1ad51104658624204d8c02f6d81840713598f02710633"
    end
    on_arm do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_linux_arm64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "da20fd65a5b93233d0a1387a1a522553f4b5251a8072abf8a8ce5be65da2cdfa"
    end
  end

  name "tuna"
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuna"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuna"]
    end
  end

  # No zap stanza required

end
