# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuna" do
  version "0.35.0"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_darwin_amd64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "f19e8743d22a3d929d8e796e35f44d937c7a3a6f1f5967fb166d4d492aab75b1"
    end
    on_arm do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_darwin_arm64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "98678bafc3dcf04780e98622d2fda55b4e8dbdb92b8452f2dce7b4270c88538a"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_linux_amd64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "91abfa68e47cebfadc209232cfbf0d816a67f980391195874d416e4648e87d1b"
    end
    on_arm do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_linux_arm64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "60860ad2115cb86d3602ae17351811d9cf64462fa2798f860a0ce536996bb996"
    end
  end

  name "tuna"
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuna"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuna"]
    end
  end

  # No zap stanza required

end
