# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuna-bastion" do
  version "0.2.3"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/bastion/v#{version}/tuna-bastion_#{version}_darwin_amd64.tar.gz"
      sha256 "6739b90e3d61bdbcf5f7328cceba3cf5ab769c5d055d744b6728a8dac62fd9be"
    end
    on_arm do
      url "https://releases.tuna.am/bastion/v#{version}/tuna-bastion_#{version}_darwin_arm64.tar.gz"
      sha256 "37fdfd32a696b9e0ad1362314446f7a92b59062b5dffa683b921296bf74e1cbf"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.tuna.am/bastion/v#{version}/tuna-bastion_#{version}_linux_amd64.tar.gz"
      sha256 "337a4e1fb414e75ae8d227ea7ad7fd45a795006d0d890043fc0c62566da1dea2"
    end
    on_arm do
      url "https://releases.tuna.am/bastion/v#{version}/tuna-bastion_#{version}_linux_arm64.tar.gz"
      sha256 "47c71fdb077bc9f3097a3555856866d78a0506bfd88cc043020cb9d92d5c200c"
    end
  end

  name "tuna-bastion"
  desc "Zero trust access to your infrastructure"
  homepage "https://tuna.am"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuna-bastion"

  # No zap stanza required

end
