# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunad" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/tunad/v#{version}/tunad_#{version}_darwin_amd64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "09d21173882b0692c4a0103bba7edf319506ea8d29d210722837b70ff596fe5c"
    end
    on_arm do
      url "https://releases.tuna.am/tunad/v#{version}/tunad_#{version}_darwin_arm64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "d327e50e59ee613de951d8e6ea3f5bc85ffcd9e9f4b8508c07f609b7b47aa3af"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.tuna.am/tunad/v#{version}/tunad_#{version}_linux_amd64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "c96f3eeaf9e0219e8ac1decdd65a2b39e563900a4736622d171e9e80979e52d8"
    end
    on_arm do
      url "https://releases.tuna.am/tunad/v#{version}/tunad_#{version}_linux_arm64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "77e74ddec7c8721ef0fb266bd95686c5516f99ab0f5b15bb176b53477416c65a"
    end
  end

  name "tunad"
  desc "Tuna Mesh Network Daemon (privileged helper for `tuna mesh`)"
  homepage "https://tuna.am"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tunad"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    tunad is a privileged mesh daemon. Set it up as a launchd service (root):

      sudo tunad install

    Manage it:
      sudo tunad status
      sudo tunad restart    # after a `brew upgrade`
      sudo tunad uninstall

    Logs: /var/log/tunad.out.log, /var/log/tunad.err.log
  EOS
end
