# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuna@0.37.0" do
  version "0.37.0"

  on_macos do
    on_arm do
      sha256 "fc3b3c3e42d3240fb9577eb9687094d500d5b08743ad550bf6113482fc853281"
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3f381c5528d4be46f2b9a5b031cbbfece5100bf71b1561828375ddec6b8f43d0"
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "43ab4ebedfaa464b0623d6373213d269638a29d1a9dd94e56131359e599702ff"
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8aceb98a4d7d061ced0e9aac8a070f877404268c2385c3355cf21462b6b7db4b"
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tuna@0.37.0"
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuna"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuna"]
    end
  end

  # No zap stanza required
end
