# This file was generated by GoReleaser. DO NOT EDIT.
cask "tuna" do
  version "0.34.2"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_darwin_amd64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "73fc782ca01585cb178b078259fd1fd936e955f0d6ce394820536e59506f1072"
    end
    on_arm do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_darwin_arm64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "2b03ef0964e9ed7755a8d37b49a7f7ec22e9a96a753e636650f125b1fd524f82"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_linux_amd64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "5f706391b30a4e014bbd57dc5e942226e8975d751961115bbab6770954d3df39"
    end
    on_arm do
      url "https://releases.tuna.am/tuna/v#{version}/tuna_#{version}_linux_arm64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "3273353c274429cf2bcd9c69e25b800cbc1e66d9269c35cf362f1900d21e1020"
    end
  end

  name "tuna"
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tuna"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tuna"]
    end
  end

  # No zap stanza required

end
