# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunad" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/tunad/v#{version}/tunad_#{version}_darwin_amd64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "7745224e4b51efd7561291e597479bfd7f8d24e4c3f3e494aa6449a0880c3e11"
    end
    on_arm do
      url "https://releases.tuna.am/tunad/v#{version}/tunad_#{version}_darwin_arm64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "7f42b6a12e4f0900e3dd5c735ec63904cbcf87c3a6e6df843be38bf38ec70232"
    end
  end

  on_linux do
    on_intel do
      url "https://releases.tuna.am/tunad/v#{version}/tunad_#{version}_linux_amd64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "a6b270d5dbea827d05e28fd987b801efc757b7b421806dd982aa334e1206e70b"
    end
    on_arm do
      url "https://releases.tuna.am/tunad/v#{version}/tunad_#{version}_linux_arm64.tar.gz",
        verified: "releases.tuna.am"
      sha256 "efb113bc119dbf5c8379e433cfa330319b1ecca60fde70aa23bdcb2eff5a4852"
    end
  end

  name "tunad"
  desc "Tuna Mesh Network Daemon (privileged helper for `tuna mesh`)"
  homepage "https://tuna.am"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tunad"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    tunad is a privileged mesh daemon. Set it up as a launchd service (root):

      sudo tunad install

    Manage it:
      sudo tunad status
      sudo tunad restart    # after a `brew upgrade`
      sudo tunad uninstall

    Logs: /var/log/tunad.out.log, /var/log/tunad.err.log
  EOS
end
