# This file was generated by GoReleaser. DO NOT EDIT.
cask "yucca@0.12.2" do
  version "0.12.2"

  on_macos do
    on_intel do
      sha256 "bb4483d7bee4bb3d6c650a6658a777e786471da2f8bea7a4b4f5c634de570a18"
      url "https://releases.yucca.app/v#{version}/yucca_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "807fec05c24f2fa6d6625ee02adeffb7823c15a0b5d6bb86da47ad440476fe28"
      url "https://releases.yucca.app/v#{version}/yucca_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "28c5b575122c0944ce3b29e5f85329cda2839a80a7bdca725ecf403b02032022"
      url "https://releases.yucca.app/v#{version}/yucca_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "888971f9fbefac1140993bf085e1868df633bec14cc05abb68706b4914f2b153"
      url "https://releases.yucca.app/v#{version}/yucca_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yucca@0.12.2"
  desc "Yucca - simple NVR CCTV solution (free edition)"
  homepage "https://yucca.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yucca"

  # No zap stanza required

end
