# This file was generated by GoReleaser. DO NOT EDIT.
cask "yucca-ent" do
  version "0.12.2"

  on_macos do
    on_intel do
      sha256 "0afae5d880798fff76a0cf1edc47840d694b17219865382bbe055287cfaa5ed4"
      url "https://releases.yucca.app/v#{version}/yucca-ent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "47c0ddb491b585f6f8791465f6ba51f4303e398fbbbf27a925f100a45b18f650"
      url "https://releases.yucca.app/v#{version}/yucca-ent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4032610026ff2fbdebbdb3a6b36e4125893564241ff4488b7d6339a977da341"
      url "https://releases.yucca.app/v#{version}/yucca-ent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec5638934dc3e0da6a5484ab7e1e3e1dc3020faaee60421dd2f8f3af8d205887"
      url "https://releases.yucca.app/v#{version}/yucca-ent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yucca-ent"
  desc "Yucca - simple NVR CCTV solution (enterprise edition)"
  homepage "https://yucca.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yucca-ent"

  # No zap stanza required

end
