# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0242 < Formula
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"
  version "0.24.2"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.24.2/tuna_0.24.2_darwin_amd64.tar.gz"
      sha256 "905519605827945bee8b2a3ea12bf5de759df8a0ae384dcef18c496fbc2d914a"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/v0.24.2/tuna_0.24.2_darwin_arm64.tar.gz"
      sha256 "994e24007cfcd7ecf7827c055ff0371ef66023ca1ef10372300f3439155d12ea"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.24.2/tuna_0.24.2_linux_amd64.tar.gz"
        sha256 "8db368a90923e773af198e05075b425a002d09d400cc3034d233153889baa7b3"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.24.2/tuna_0.24.2_linux_arm.tar.gz"
        sha256 "a137c0ba4c1ac24fe07baef04a0d0b56f73d4f818505f10926422f22502b5ec2"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.24.2/tuna_0.24.2_linux_arm64.tar.gz"
        sha256 "86428c5a6bea0c0da1141b5ef9607ef623830cba28f1a35a8ee3e129110a473a"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
