# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0300 < Formula
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"
  version "0.30.0"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.30.0/tuna_0.30.0_darwin_amd64.tar.gz"
      sha256 "8ffebda9d3136db8e00fdd07948de0676f09123bce0b869228a1ece5246948fe"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/v0.30.0/tuna_0.30.0_darwin_arm64.tar.gz"
      sha256 "cd67fe0ed6836262cbbf1b3c455ba83c4fefa82ac94612d602f743479c2d8c5c"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.30.0/tuna_0.30.0_linux_amd64.tar.gz"
        sha256 "833ca231209c7155ac2a4b531ca43d0c63ac714bda4fe2da4af04c5662c7a9f2"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.30.0/tuna_0.30.0_linux_arm.tar.gz"
        sha256 "b212ce76936763e2ebfc006a77eb445e94777ff972887ba46303ca77cefe6492"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.30.0/tuna_0.30.0_linux_arm64.tar.gz"
        sha256 "31f248b549ec5eb4740c881941382b736aad0380e8a86da33b44c5e1332afe08"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
