# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0240 < Formula
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"
  version "0.24.0"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.24.0/tuna_0.24.0_darwin_amd64.tar.gz"
      sha256 "b2b5640f5c26439163f60d9c1eb7410e46f764eb46d2398aede858587e9d8a69"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/v0.24.0/tuna_0.24.0_darwin_arm64.tar.gz"
      sha256 "ea6aeff99379e4ab289bffbe9ce8e115cdd0f5bf3ea12c9eaaa17431061f9e17"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.24.0/tuna_0.24.0_linux_amd64.tar.gz"
        sha256 "76b88278e33f02784a71c2624ba6f3d7ed3a3c0c75f94edbe147bafa0b09ca99"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.24.0/tuna_0.24.0_linux_arm.tar.gz"
        sha256 "16353889d5a29422820e14ef981ee89066de53ad96c1771f00975b7e804769f8"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.24.0/tuna_0.24.0_linux_arm64.tar.gz"
        sha256 "40966ca143c31098918d8367162dfc025e151c54d7a958330766f39f104ccaba"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
