# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0190 < Formula
  desc "Tuna - software for create HTTP/TCP tunnels to local network"
  homepage "https://tuna.am"
  version "0.19.0"
  license "Copyright YuccaStream Team (https://tuna.am/tos.html)"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/tuna/v0.19.0/tuna_0.19.0_darwin_amd64.tar.gz"
      sha256 "e1c65cd2f757f6025e8f8a1d9148d3da45f43fcf625654bb2fe1b975ceb5c307"

      def install
        bin.install "tuna"
      end
    end
    on_arm do
      url "https://releases.tuna.am/tuna/v0.19.0/tuna_0.19.0_darwin_arm64.tar.gz"
      sha256 "eda28fb8eaba5aea0ab46e7abba2d244125be5e46a15c2e6a9ec351e4b0593fe"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.19.0/tuna_0.19.0_linux_amd64.tar.gz"
        sha256 "d308c650946e19653c3948f31ba85a0cc0834b779e887ce0f620721fa577aa69"

        def install
          bin.install "tuna"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.19.0/tuna_0.19.0_linux_arm.tar.gz"
        sha256 "ebbcde59297582495e0c0bcb3d11970ba343cb1eb0a24a361aa57b0eda17b79a"

        def install
          bin.install "tuna"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.19.0/tuna_0.19.0_linux_arm64.tar.gz"
        sha256 "15c0e6dd1a24900261a28e77435686f6afa93680b27c8f85cb468d079704e246"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
