# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0160 < Formula
  desc "Tuna - software for create HTTP/TCP tunnels to local network"
  homepage "https://tuna.am"
  version "0.16.0"
  license "Copyright YuccaStream Team (https://tuna.am/tos.html)"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/tuna/0.16.0/tuna_0.16.0_darwin_amd64.tar.gz"
      sha256 "4a7a47f8d4331232a1148cb3079180b8301300df76c855108a70dd5e64751f42"

      def install
        bin.install "tuna"
      end
    end
    on_arm do
      url "https://releases.tuna.am/tuna/0.16.0/tuna_0.16.0_darwin_arm64.tar.gz"
      sha256 "78589f725cf543e2ba2a3c2661fd453a22bed5bc606d552360683577cb9aac6d"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/0.16.0/tuna_0.16.0_linux_amd64.tar.gz"
        sha256 "6bbfc855e9c279dba74d9351429da8593bd8b7ef035b7ce1297f72ebfc7f46f8"

        def install
          bin.install "tuna"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/0.16.0/tuna_0.16.0_linux_arm.tar.gz"
        sha256 "4c24309225d2a923dcf0141acd7ab3a8c0a61cbfa945d163811498d6f9549673"

        def install
          bin.install "tuna"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/0.16.0/tuna_0.16.0_linux_arm64.tar.gz"
        sha256 "8cafe6560c08e87f6cae5f2e87b486b5befc9a3716eb69f4532968b703f5e58b"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
