# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0170 < Formula
  desc "Tuna - software for create HTTP/TCP tunnels to local network"
  homepage "https://tuna.am"
  version "0.17.0"
  license "Copyright YuccaStream Team (https://tuna.am/tos.html)"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/tuna/v0.17.0/tuna_0.17.0_darwin_amd64.tar.gz"
      sha256 "dd4f3ac8dec0edb3e0b9018f09fe9ee238d36878e7363d53a3619b34be4cb9c8"

      def install
        bin.install "tuna"
      end
    end
    on_arm do
      url "https://releases.tuna.am/tuna/v0.17.0/tuna_0.17.0_darwin_arm64.tar.gz"
      sha256 "4e820f6ca112b1785f32c3a62671b608bb2c2eabfd575b2fff492967bf1fd4bd"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.17.0/tuna_0.17.0_linux_amd64.tar.gz"
        sha256 "f2df51238361b6f97034fb1a55498fa740fa7f991047fc5df49712f76e1660d5"

        def install
          bin.install "tuna"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.17.0/tuna_0.17.0_linux_arm.tar.gz"
        sha256 "3dedf6755275186933f19195cad0fc98ec5c1c418740fdd547eb5529daf9ab8b"

        def install
          bin.install "tuna"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.17.0/tuna_0.17.0_linux_arm64.tar.gz"
        sha256 "526678f267becdef1aa411f795ec53f8a8bf38ff64a7448666311cf5c3246de0"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
