# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0330 < Formula
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"
  version "0.33.0"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.33.0/tuna_0.33.0_darwin_amd64.tar.gz"
      sha256 "a4ce927733201a3ccf09bc722f698985e6c314e1b8f1febdef6c1c8942d53534"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/v0.33.0/tuna_0.33.0_darwin_arm64.tar.gz"
      sha256 "866e4f2b18849096a013853a842a1541a5d10e8ef1be987157eafdc0ad68f283"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.33.0/tuna_0.33.0_linux_amd64.tar.gz"
        sha256 "7246d9d74f9de248b1a6aaa4c4f208f2dfa4fc8e2adcd06254a58e6bcd717741"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.33.0/tuna_0.33.0_linux_armv7.tar.gz"
        sha256 "a96e97531b9165cf131af9cf9fe515cd6eb9defd001c7787a37f29b48a5ff251"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.33.0/tuna_0.33.0_linux_arm64.tar.gz"
        sha256 "c532f8d9b742a7c3f34fb9822c24e0b36bf8e7a81ebbd79648d2209148c89f79"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
