# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0154 < Formula
  desc "Tuna - software for create HTTP/TCP tunnels to local network"
  homepage "https://tuna.am"
  version "0.15.4"
  license "Copyright YuccaStream Team (https://tuna.am/tos.html)"

  on_macos do
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/v0.15.4/tuna_0.15.4_darwin_arm64.tar.gz"
      sha256 "2a7449943624ad5a9904d5006c0aa927f7d8da874ab99795afb3022923801a79"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.15.4/tuna_0.15.4_darwin_amd64.tar.gz"
      sha256 "76d41cbdf625f8f31bf8f9cb53b9748d34ba93f3b6c11988103898a84764084c"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://releases.tuna.am/tuna/v0.15.4/tuna_0.15.4_linux_arm.tar.gz"
      sha256 "fc5db393da710d943746f86c63a7c77dab4aabe9b59b2061fbbe4c3b13b99ba8"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.tuna.am/tuna/v0.15.4/tuna_0.15.4_linux_arm64.tar.gz"
      sha256 "2148f2900e2d5232c91247b8fb8c1e28da49e3ea455ec499446fe0dac8e540e8"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.15.4/tuna_0.15.4_linux_amd64.tar.gz"
      sha256 "141637c5fa8e94fb63c5684895ce5b1cf9bedb22c294303d6635337d3754ae33"

      def install
        bin.install "tuna"
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
