# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0151Beta2 < Formula
  desc "Tuna - software for create HTTP/TCP tunnels to local network"
  homepage "https://tuna.am"
  version "0.15.1-beta2"
  license "Copyright YuccaStream Team (https://tuna.am/tos.html)"

  on_macos do
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/beta/v0.15.1-beta2/tuna_0.15.1-beta2_darwin_arm64.tar.gz"
      sha256 "b2a807e30f96fc7e68d2d4d9dbb43209e47dd7a82f5dd492a2c8bc464a1eb0b8"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/beta/v0.15.1-beta2/tuna_0.15.1-beta2_darwin_amd64.tar.gz"
      sha256 "1090fbfc32edf38563ef18981cb6c1daa5e40b4854e832fcf1791b9e9b707a52"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://releases.tuna.am/tuna/beta/v0.15.1-beta2/tuna_0.15.1-beta2_linux_arm.tar.gz"
      sha256 "b8fc2e47e304b26b9c06a1e29c97291e7b718cc99050b21eb7cf4109dd9698aa"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.tuna.am/tuna/beta/v0.15.1-beta2/tuna_0.15.1-beta2_linux_arm64.tar.gz"
      sha256 "80dc8b944f02ab629d3409ed750a5415d9b8c4d6874a865d203f9a2f2df3e6b6"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/beta/v0.15.1-beta2/tuna_0.15.1-beta2_linux_amd64.tar.gz"
      sha256 "b8904a923a49983fd85b68bf2f1962aeca3109849f87016c4889a9ef60560c49"

      def install
        bin.install "tuna"
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
