# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0210 < Formula
  desc "Tuna - software for create HTTP/TCP tunnels to local network"
  homepage "https://tuna.am"
  version "0.21.0"
  license "Copyright YuccaStream Team (https://tuna.am/tos.html)"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/tuna/v0.21.0/tuna_0.21.0_darwin_amd64.tar.gz"
      sha256 "841db864356558ba42d02cc6e9addb598677b43dfcb02e7f28690dcca16f0ad6"

      def install
        bin.install "tuna"
      end
    end
    on_arm do
      url "https://releases.tuna.am/tuna/v0.21.0/tuna_0.21.0_darwin_arm64.tar.gz"
      sha256 "dca50a78c625ee27288b23e802689befefd75ae1fc07ac8f194ac9fdf7f91128"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.21.0/tuna_0.21.0_linux_amd64.tar.gz"
        sha256 "643dcfa869e139ef991df63965e60794d31f0c8e84da133918fa5765176ac1c8"

        def install
          bin.install "tuna"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.21.0/tuna_0.21.0_linux_arm.tar.gz"
        sha256 "97bed7932e7eef554fe75fc4d579887214489dac0180a7dd5ec1834158560937"

        def install
          bin.install "tuna"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.21.0/tuna_0.21.0_linux_arm64.tar.gz"
        sha256 "4820d90dd39f08f53b9c095b6b5bb8e516bcb4d8828a6e937913ba7ee01c7ce7"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
