# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0272 < Formula
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"
  version "0.27.2"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.27.2/tuna_0.27.2_darwin_amd64.tar.gz"
      sha256 "ec9af42c01e58c5258565cd9526359286ccd9e980c4813de3b680ac846f71b16"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/v0.27.2/tuna_0.27.2_darwin_arm64.tar.gz"
      sha256 "5e621ac7da0b2d0b91ecc2a378de72e65cb23c875859deb28ca73f21326d2aa7"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.27.2/tuna_0.27.2_linux_amd64.tar.gz"
        sha256 "3e516823a6e2a67564f7e53469798f9741b1a5bf1f1008b6388988b47401c670"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.27.2/tuna_0.27.2_linux_arm.tar.gz"
        sha256 "ea7adf7e3b7b2f358f7630c8df80292f67c5b9d3a3d069bac10455b474b2ed13"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.27.2/tuna_0.27.2_linux_arm64.tar.gz"
        sha256 "dcab74d5bb8c8f3eb2d5b7c9209a3bb72509eb1a688340a73134e7b2c9705159"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
