# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0161 < Formula
  desc "Tuna - software for create HTTP/TCP tunnels to local network"
  homepage "https://tuna.am"
  version "0.16.1"
  license "Copyright YuccaStream Team (https://tuna.am/tos.html)"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/tuna/v0.16.1/tuna_0.16.1_darwin_amd64.tar.gz"
      sha256 "6777c7ae4aa292bd2e0daac6358de2e99b3cd1c1a5dd2372d5083c51c460cd85"

      def install
        bin.install "tuna"
      end
    end
    on_arm do
      url "https://releases.tuna.am/tuna/v0.16.1/tuna_0.16.1_darwin_arm64.tar.gz"
      sha256 "d2b6a996d4c4c179bf471e3eba7a45698f1ecbdf7b3ca590a9351452685fc31f"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.16.1/tuna_0.16.1_linux_amd64.tar.gz"
        sha256 "66050bc67c71a3c8577e32ae546a78c2cc5c9d7859b0654ab18e5df27218d56c"

        def install
          bin.install "tuna"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.16.1/tuna_0.16.1_linux_arm.tar.gz"
        sha256 "0f9129cd0085c51f094afbc74bac6531e9e68c1ec4c0decc5ed5736635369a18"

        def install
          bin.install "tuna"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.16.1/tuna_0.16.1_linux_arm64.tar.gz"
        sha256 "d1c14986939abbe4f99bcfd22b834466f6a56ec44b84dce7ab0d48e256273d3b"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
