# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0212 < Formula
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"
  version "0.21.2"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.21.2/tuna_0.21.2_darwin_amd64.tar.gz"
      sha256 "17686fe8cf6fa05a26fc38a017461b5b7038587ecf1aa3c8c0343369393318f6"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/v0.21.2/tuna_0.21.2_darwin_arm64.tar.gz"
      sha256 "fbec566a1777a186a9be0c35d32757d8f9f45041550f16761549795cbd514eeb"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.21.2/tuna_0.21.2_linux_amd64.tar.gz"
        sha256 "e341d2582f7618bd8caaf8fd79c8f8fe7a7ec305a3994a3ffbc0097bc4255e1f"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.21.2/tuna_0.21.2_linux_arm.tar.gz"
        sha256 "37e8450ed8974064791dfe13acdc0a1f36135b29dab4de0b5b082ac1f4ddaf77"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.21.2/tuna_0.21.2_linux_arm64.tar.gz"
        sha256 "b40c22148658794684aec5eeb20df2a16fc1ef042bea4bc9da2b33f1180f71b3"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
