# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuna < Formula
  desc "Tuna - software for create HTTP/TCP tunnels to local network"
  homepage "https://tuna.am"
  version "0.15.6"
  license "Copyright YuccaStream Team (https://tuna.am/tos.html)"

  on_macos do
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/v0.15.6/tuna_0.15.6_darwin_arm64.tar.gz"
      sha256 "5cdd25520c4283efbebc8b433c5203bbb03ddab31994b5ae184968547b0696ed"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.15.6/tuna_0.15.6_darwin_amd64.tar.gz"
      sha256 "0a43b28b34975933b053b2c117d5fa8c38cabd5cdd4c7251b6b81c69889700a9"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://releases.tuna.am/tuna/v0.15.6/tuna_0.15.6_linux_arm.tar.gz"
      sha256 "53958d6279c75b877ec71af415840cec4dc3899d1c0fee2f847d293bcb1e496f"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.15.6/tuna_0.15.6_linux_amd64.tar.gz"
      sha256 "6c75f3aab807dcb7b2027dff70a5f8ba66110b8720819699c87fb74f8c8dec89"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.tuna.am/tuna/v0.15.6/tuna_0.15.6_linux_arm64.tar.gz"
      sha256 "1f6fb137c12cf042a83cb249b18c447f93638233ee5d4d72da1993f4a9841db4"

      def install
        bin.install "tuna"
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
