# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuna < Formula
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"
  version "0.24.3"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.24.3/tuna_0.24.3_darwin_amd64.tar.gz"
      sha256 "3eeaf56203c14cb9ff0196b86ee75c70bee7a9643edb6e7e5f0d70775c501cec"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/v0.24.3/tuna_0.24.3_darwin_arm64.tar.gz"
      sha256 "90e46330b4cc1ebd0264475e48b2baa3866a8bbe8085697f3cd2adc69ff8497a"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.24.3/tuna_0.24.3_linux_amd64.tar.gz"
        sha256 "82e0cdbc5d80320eeb7321c6191a202cc54fcea661c08909ee427100e327101e"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.24.3/tuna_0.24.3_linux_arm.tar.gz"
        sha256 "98faf2c236de0c5547890a371ea815323e934038094993498d16328a8630a2c2"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.24.3/tuna_0.24.3_linux_arm64.tar.gz"
        sha256 "68570df546d066eb8a2c7ab8dd109499847dd4b94b3ce0bba4a92f9bcaa55e05"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
