# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0250 < Formula
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"
  version "0.25.0"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.25.0/tuna_0.25.0_darwin_amd64.tar.gz"
      sha256 "bbf322840d95725776ddb98bec575c14a37d32509b3357f82ad23ff6268eee2d"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/v0.25.0/tuna_0.25.0_darwin_arm64.tar.gz"
      sha256 "0817cf6fd9a0f1fbaafcbe2aaa0d789f0fce12e8c2a7fa618bfb089906fa5f1e"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.25.0/tuna_0.25.0_linux_amd64.tar.gz"
        sha256 "fb85ff8ca9ff4dfc9c71906b1565dca82177bd7dbcecd8f5a68a7682985b491c"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.25.0/tuna_0.25.0_linux_arm.tar.gz"
        sha256 "1d7e4f4828640ff55709131bb1b44ad65755797dc04395908f49bc08b09b4cb6"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.25.0/tuna_0.25.0_linux_arm64.tar.gz"
        sha256 "35c4b3edeb62b80bf34ff3b38f4ad7fcf1736161e43a11a48f10e036100a6165"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
