# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TunaAT0270 < Formula
  desc "Tuna - software for create HTTP/TCP/SSH tunnels to local network"
  homepage "https://tuna.am"
  version "0.27.0"
  license "proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/v0.27.0/tuna_0.27.0_darwin_amd64.tar.gz"
      sha256 "e8da687ae68f57e49260a9dd80eb2a9ee71d76ac8a48616f51f7ce033dfe8001"

      def install
        bin.install "tuna"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/v0.27.0/tuna_0.27.0_darwin_arm64.tar.gz"
      sha256 "0c72606863dc816306dffde0020725319624ba8b693e751bfefaad888e3609df"

      def install
        bin.install "tuna"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.27.0/tuna_0.27.0_linux_amd64.tar.gz"
        sha256 "87e5b6f1d437dd53d661971b2199df620bdd5219b03321ef2648df51b9c3684d"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.27.0/tuna_0.27.0_linux_arm.tar.gz"
        sha256 "0415a68815b33ce5cc9ccf462b36b1db583903abefe70ffed00e0ad47c38ecfb"

        def install
          bin.install "tuna"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/tuna/v0.27.0/tuna_0.27.0_linux_arm64.tar.gz"
        sha256 "f1f961614a6621a867628f9f64b43570af4fd570dbff5b0f68c88f73b7333a86"

        def install
          bin.install "tuna"
        end
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
