# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuna < Formula
  desc "Tuna - software for create HTTP/TCP tunnels to local network"
  homepage "https://tuna.am"
  version "0.15.1-beta6"
  license "Copyright YuccaStream Team (https://tuna.am/tos.html)"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/beta/v0.15.1-beta6/tuna_0.15.1-beta6_darwin_amd64.tar.gz"
      sha256 "0574aba1e5d29f8cbca7619ed4e7f783cee7480c4f05fd6064b923b2407ea6ca"

      def install
        bin.install "tuna"
        (bash_completion/"tuna.sh").write `#{bin}/tuna completion bash`
        (zsh_completion/"_tuna").write `#{bin}/tuna completion zsh`
        (fish_completion/"tuna.fish").write `#{bin}/tuna completion fish`
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.tuna.am/tuna/beta/v0.15.1-beta6/tuna_0.15.1-beta6_darwin_arm64.tar.gz"
      sha256 "2a182ca0352c3ae85979e9440808771d7cb10c18e4df448c8cc31722913141e2"

      def install
        bin.install "tuna"
        (bash_completion/"tuna.sh").write `#{bin}/tuna completion bash`
        (zsh_completion/"_tuna").write `#{bin}/tuna completion zsh`
        (fish_completion/"tuna.fish").write `#{bin}/tuna completion fish`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://releases.tuna.am/tuna/beta/v0.15.1-beta6/tuna_0.15.1-beta6_linux_arm.tar.gz"
      sha256 "3c308f7f8bce94bb663b3f2f051393dc3c8a10974af0da9f39f101b4ba16d508"

      def install
        bin.install "tuna"
        (bash_completion/"tuna.sh").write `#{bin}/tuna completion bash`
        (zsh_completion/"_tuna").write `#{bin}/tuna completion zsh`
        (fish_completion/"tuna.fish").write `#{bin}/tuna completion fish`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.tuna.am/tuna/beta/v0.15.1-beta6/tuna_0.15.1-beta6_linux_arm64.tar.gz"
      sha256 "b77c072029a80535108db5cc7576f341e600cf448368089e2e223ee5f677e0d3"

      def install
        bin.install "tuna"
        (bash_completion/"tuna.sh").write `#{bin}/tuna completion bash`
        (zsh_completion/"_tuna").write `#{bin}/tuna completion zsh`
        (fish_completion/"tuna.fish").write `#{bin}/tuna completion fish`
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.tuna.am/tuna/beta/v0.15.1-beta6/tuna_0.15.1-beta6_linux_amd64.tar.gz"
      sha256 "fb9c8cb08bbf805ef66d2bf8e3d696934b3437cb5482b020ad671ec3aeb36176"

      def install
        bin.install "tuna"
        (bash_completion/"tuna.sh").write `#{bin}/tuna completion bash`
        (zsh_completion/"_tuna").write `#{bin}/tuna completion zsh`
        (fish_completion/"tuna.fish").write `#{bin}/tuna completion fish`
      end
    end
  end

  test do
    system "#{bin}/tuna version"
  end
end
