# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yucca < Formula
  desc "Yucca - simple NVR CCTV solution (free edition)"
  homepage "https://yucca.app"
  version "0.11.5"
  license "Copyright YuccaStream Team (https://yucca.app/en/terms)"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.yucca.app/v0.11.5/yucca_0.11.5_darwin_amd64.tar.gz"
      sha256 "5a75d6ca9cb648f47b5c65b139e19755e6a4a870aea2a8ae21589f054b80cdcd"

      def install
        bin.install "yucca"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.yucca.app/v0.11.5/yucca_0.11.5_darwin_arm64.tar.gz"
      sha256 "9f5754858fcec03abff22987b0763e4da70f798fcbf44a67e68ff2f64aa71c9f"

      def install
        bin.install "yucca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.11.5/yucca_0.11.5_linux_amd64.tar.gz"
        sha256 "66d70d7d2fe353ab628d45534d50271a3c511d76edd01d05426cef3f8e250c98"

        def install
          bin.install "yucca"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.11.5/yucca_0.11.5_linux_arm.tar.gz"
        sha256 "ccc7f1c06a923d9cb4fb612f78de81a0c5a914dcfe344b646ac5e79d2f767766"

        def install
          bin.install "yucca"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.11.5/yucca_0.11.5_linux_arm64.tar.gz"
        sha256 "3b302be51a2076085b0f8bab241b1a8411b948a1b7a18fc17a6f6bd21a4741e2"

        def install
          bin.install "yucca"
        end
      end
    end
  end

  test do
    system "#{bin}/yucca version"
  end
end
