# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YuccaAT0101 < Formula
  desc "Yucca - simple NVR CCTV solution (free edition)"
  homepage "https://yucca.app"
  version "0.10.1"
  license "Copyright YuccaStream Team (https://yucca.app/en/terms)"

  on_macos do
    on_intel do
      url "https://releases.yucca.app/v0.10.1/yucca_0.10.1_darwin_amd64.tar.gz"
      sha256 "fd6c86bfae551bea67d9370c1f506311442cea1a8e5810aa9b6f753e0f1bf10c"

      def install
        bin.install "yucca"
      end
    end
    on_arm do
      url "https://releases.yucca.app/v0.10.1/yucca_0.10.1_darwin_arm64.tar.gz"
      sha256 "237fa5f6daca00559081fe4603b3e5e7250a8cb00c0c50e78fa3f5118c6abb42"

      def install
        bin.install "yucca"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.1/yucca_0.10.1_linux_amd64.tar.gz"
        sha256 "7cf9b9e2a29305dbbdf5b8fc713c507b28ee889f30968ee7a54254a6cb802762"

        def install
          bin.install "yucca"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.1/yucca_0.10.1_linux_arm.tar.gz"
        sha256 "6490997488e0095cfc7119232290f3fdf50a53f4741b45ea901c5e8f509b84f5"

        def install
          bin.install "yucca"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.1/yucca_0.10.1_linux_arm64.tar.gz"
        sha256 "b85601c443d99d9720898235aa0d38bd35470dc1f3387042c6adec45278ef8e7"

        def install
          bin.install "yucca"
        end
      end
    end
  end

  test do
    system "#{bin}/yucca version"
  end
end
