# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YuccaAT0101Alpha1 < Formula
  desc "Yucca - simple NVR CCTV solution (free edition)"
  homepage "https://yucca.app"
  version "0.10.1-alpha1"
  license "Copyright YuccaStream Team (https://yucca.app/en/terms)"
  depends_on :macos

  on_arm do
    url "https://releases.yucca.app/beta/v0.10.1-alpha1/yucca_0.10.1-alpha1_darwin_arm64.tar.gz"
    sha256 "37342cd6562c307b3c67214a32e55d8c42282114f151d675c658bc5719955c1e"

    def install
      bin.install "yucca"
    end
  end

  test do
    system "#{bin}/yucca version"
  end
end
