# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YuccaAT0102 < Formula
  desc "Yucca - simple NVR CCTV solution (free edition)"
  homepage "https://yucca.app"
  version "0.10.2"
  license "Copyright YuccaStream Team (https://yucca.app/en/terms)"

  on_macos do
    on_intel do
      url "https://releases.yucca.app/v0.10.2/yucca_0.10.2_darwin_amd64.tar.gz"
      sha256 "04bd9754736051ac78eae2fbda5c401bf3042391dfd438cb11ea12c2daeb2886"

      def install
        bin.install "yucca"
      end
    end
    on_arm do
      url "https://releases.yucca.app/v0.10.2/yucca_0.10.2_darwin_arm64.tar.gz"
      sha256 "3cbce33e26921e11e13f8ca67faceee758076fd08ed02f0c7b5a4bbefa753f53"

      def install
        bin.install "yucca"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.2/yucca_0.10.2_linux_amd64.tar.gz"
        sha256 "9c2d32c35e0e9e8803c4d061b3aa0512eb78257d2a67b653be11dce61801e9c0"

        def install
          bin.install "yucca"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.2/yucca_0.10.2_linux_arm.tar.gz"
        sha256 "2a7668adef6fecb7f9b526a5e63a99431b1c38d9594d0521c617774785001a3b"

        def install
          bin.install "yucca"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.2/yucca_0.10.2_linux_arm64.tar.gz"
        sha256 "83cc6f14479128bba066896f0fe60ab8d0a2bcefca7c85825d6b1d9d60678382"

        def install
          bin.install "yucca"
        end
      end
    end
  end

  test do
    system "#{bin}/yucca version"
  end
end
