# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YuccaEnt < Formula
  desc "Yucca - simple NVR CCTV solution (enterprise edition)"
  homepage "https://yucca.app"
  version "0.10.1-alpha1"
  license "Copyright YuccaStream Team (https://yucca.app/en/terms)"
  depends_on :macos

  on_arm do
    url "https://releases.tuna.am/beta/v0.10.1-alpha1/yucca-ent_0.10.1-alpha1_darwin_arm64.tar.gz"
    sha256 "ea34c3794984385e6d997411ccd99d9234a7b77043d34ea84853524a4fb7cb2d"

    def install
      bin.install "yucca"
    end
  end

  test do
    system "#{bin}/yucca version"
  end
end
