# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YuccaEntAT0104 < Formula
  desc "Yucca - simple NVR CCTV solution (enterprise edition)"
  homepage "https://yucca.app"
  version "0.10.4"
  license "Copyright YuccaStream Team (https://yucca.app/en/terms)"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.yucca.app/v0.10.4/yucca-ent_0.10.4_darwin_amd64.tar.gz"
      sha256 "b8a34e68f34efd138b89efcab308907e4d488c25118274e31b9c19b8df330ab8"

      def install
        bin.install "yucca"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.yucca.app/v0.10.4/yucca-ent_0.10.4_darwin_arm64.tar.gz"
      sha256 "303568dd16d44afe705a2017bd6ffbd7e2d8d690e594342f6ccc680e150786bc"

      def install
        bin.install "yucca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.4/yucca-ent_0.10.4_linux_amd64.tar.gz"
        sha256 "7df8fdef111cdb9b8b45d62705ff6093bba4de15e6fa06d75e7b1a52d912bc2e"

        def install
          bin.install "yucca"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.4/yucca-ent_0.10.4_linux_arm.tar.gz"
        sha256 "8d4960f1c6deb4af8aa98840734f1453862cd0b97d73275025442d809eef602f"

        def install
          bin.install "yucca"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.4/yucca-ent_0.10.4_linux_arm64.tar.gz"
        sha256 "1cf65235415c5849d4ced1b6e5eb10e5dd05551990f8a4ad5120bfc0f58e584c"

        def install
          bin.install "yucca"
        end
      end
    end
  end

  test do
    system "#{bin}/yucca version"
  end
end
