# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YuccaEnt < Formula
  desc "Yucca - simple NVR CCTV solution (enterprise edition)"
  homepage "https://yucca.app"
  version "0.10.1"
  license "Copyright YuccaStream Team (https://yucca.app/en/terms)"

  on_macos do
    on_intel do
      url "https://releases.tuna.am/v0.10.1/yucca-ent_0.10.1_darwin_amd64.tar.gz"
      sha256 "318d2063d65d0e29634f2ca11497556bc19554cc6be96c948b97a4c84254c47a"

      def install
        bin.install "yucca"
      end
    end
    on_arm do
      url "https://releases.tuna.am/v0.10.1/yucca-ent_0.10.1_darwin_arm64.tar.gz"
      sha256 "4d32ea3537956dedbdff4369ec66135858733fc867df397284a3cceefe8c2ab1"

      def install
        bin.install "yucca"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/v0.10.1/yucca-ent_0.10.1_linux_amd64.tar.gz"
        sha256 "5a8ba9d835e457abd4a4b0d16e44c4173b517886cf83815dd790c643341fd10e"

        def install
          bin.install "yucca"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/v0.10.1/yucca-ent_0.10.1_linux_arm.tar.gz"
        sha256 "af390e50ddca4e2bf0c43fbebbb8f7dc283a9fbc6707940059a530009b7ec82a"

        def install
          bin.install "yucca"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.tuna.am/v0.10.1/yucca-ent_0.10.1_linux_arm64.tar.gz"
        sha256 "72b9e6ca5e7456591b5c6cd697f5c8f34d60305725f5fee10cd00b190e25881c"

        def install
          bin.install "yucca"
        end
      end
    end
  end

  test do
    system "#{bin}/yucca version"
  end
end
