# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YuccaAT0101 < Formula
  desc "Yucca - simple NVR CCTV solution (free edition)"
  homepage "https://yucca.app"
  version "0.10.1"
  license "Copyright YuccaStream Team (https://yucca.app/en/terms)"

  on_macos do
    on_intel do
      url "https://releases.yucca.app/v0.10.1/yucca_0.10.1_darwin_amd64.tar.gz"
      sha256 "07479718b01d9c66f8f66ad1ab08804f691967714bdacb3b639ab40eb73e8bae"

      def install
        bin.install "yucca"
      end
    end
    on_arm do
      url "https://releases.yucca.app/v0.10.1/yucca_0.10.1_darwin_arm64.tar.gz"
      sha256 "bc14acfae059e1d388bdbbc11ce68e4d8c1366e3f8fba791302507d4aca79c54"

      def install
        bin.install "yucca"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.1/yucca_0.10.1_linux_amd64.tar.gz"
        sha256 "7a238d057e729559609c7e1e5c0414b35e93d22a14bf7e96bdb9fb60b38a6304"

        def install
          bin.install "yucca"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.1/yucca_0.10.1_linux_arm.tar.gz"
        sha256 "be0ba415dbd1e38b8507b38aa54c25b07393cb92d4bf91c705c55b914d15e9eb"

        def install
          bin.install "yucca"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.1/yucca_0.10.1_linux_arm64.tar.gz"
        sha256 "955e8581418a4e97c3794ed899e6c5bd3a18dc01a321ced6c7fdf79c9c0a7360"

        def install
          bin.install "yucca"
        end
      end
    end
  end

  test do
    system "#{bin}/yucca version"
  end
end
