# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YuccaEnt < Formula
  desc "Yucca - simple NVR CCTV solution (enterprise edition)"
  homepage "https://yucca.app"
  version "0.11.3"
  license "Copyright YuccaStream Team (https://yucca.app/en/terms)"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.yucca.app/v0.11.3/yucca-ent_0.11.3_darwin_amd64.tar.gz"
      sha256 "ef255d6634480ded7362596b9f5efa2569a414baa5ad22960b111bc1a7810e2b"

      def install
        bin.install "yucca"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.yucca.app/v0.11.3/yucca-ent_0.11.3_darwin_arm64.tar.gz"
      sha256 "5e09c89858dc362869fecac0f3c96212fa8688ac16b2b488c0a06c6c13d79cbe"

      def install
        bin.install "yucca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.11.3/yucca-ent_0.11.3_linux_amd64.tar.gz"
        sha256 "72337029211b62cf5d35f6414712ceb5bb701c73d7fbf7d85368a9444adba3c8"

        def install
          bin.install "yucca"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.11.3/yucca-ent_0.11.3_linux_arm.tar.gz"
        sha256 "07acf5b3297390aaf63fe64ab1729565baa4411c0ba2f2c08cd034b0ede2a6e5"

        def install
          bin.install "yucca"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.11.3/yucca-ent_0.11.3_linux_arm64.tar.gz"
        sha256 "6023a9190ff2ff4b7507a5b726444e54bc7b3bfc9d59c33771c6e1e893c49700"

        def install
          bin.install "yucca"
        end
      end
    end
  end

  test do
    system "#{bin}/yucca version"
  end
end
