# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yucca < Formula
  desc "Yucca - simple NVR CCTV solution (free edition)"
  homepage "https://yucca.app"
  version "0.10.4"
  license "Copyright YuccaStream Team (https://yucca.app/en/terms)"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.yucca.app/v0.10.4/yucca_0.10.4_darwin_amd64.tar.gz"
      sha256 "d07e0907f87f6465e53629a8f45fb60f3f1b7667b46ddcfa5e5d69553dd54dde"

      def install
        bin.install "yucca"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.yucca.app/v0.10.4/yucca_0.10.4_darwin_arm64.tar.gz"
      sha256 "269ffee517f07e76b28f76daf292ef5d400145d00420d43be509bd40be66efa7"

      def install
        bin.install "yucca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.4/yucca_0.10.4_linux_amd64.tar.gz"
        sha256 "a96da15d5721e95bd6008cb850d6a6f8a234309e2f4bebee2a11061665a43746"

        def install
          bin.install "yucca"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.4/yucca_0.10.4_linux_arm.tar.gz"
        sha256 "4196c2ad5fd469953d7a7f93d6633258221c68a2613043eaee4c3d7f95be4021"

        def install
          bin.install "yucca"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.10.4/yucca_0.10.4_linux_arm64.tar.gz"
        sha256 "4438a109d4ed7ed56ad84f972f489b7af7347cec557cf9447e72f5d3d141779b"

        def install
          bin.install "yucca"
        end
      end
    end
  end

  test do
    system "#{bin}/yucca version"
  end
end
