# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YuccaEntAT0123 < Formula
  desc "Yucca - simple NVR CCTV solution (enterprise edition)"
  homepage "https://yucca.app"
  version "0.12.3"
  license "Copyright YuccaStream Team (https://yucca.app/en/terms)"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.yucca.app/v0.12.3/yucca-ent_0.12.3_darwin_amd64.tar.gz"
      sha256 "84c882369ae8ea48a523d648ef09c1e1ca71f0a047b469d995fe58c350b8e316"

      def install
        bin.install "yucca"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.yucca.app/v0.12.3/yucca-ent_0.12.3_darwin_arm64.tar.gz"
      sha256 "b7bc86f613828dfd917f7f2058c421b945e68fb34a51c4a551971677fe6017d1"

      def install
        bin.install "yucca"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.12.3/yucca-ent_0.12.3_linux_amd64.tar.gz"
        sha256 "96d4eb3ce384ec1cc0511153c0cb3f50358ec6d12822f13d271741b0b52f0bc4"

        def install
          bin.install "yucca"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.12.3/yucca-ent_0.12.3_linux_arm.tar.gz"
        sha256 "906074ce3a52be2424adf60c1672cfef667b4cf14e6fdc3f79ebabcbbe8d6f47"

        def install
          bin.install "yucca"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://releases.yucca.app/v0.12.3/yucca-ent_0.12.3_linux_arm64.tar.gz"
        sha256 "6261b41f29941dc5e862be74b5d03749f2f6b9df65187e5657e061062750a3bc"

        def install
          bin.install "yucca"
        end
      end
    end
  end

  test do
    system "#{bin}/yucca version"
  end
end
